<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPssi3z9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPssi3z9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPssi3z9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPssi3z9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPssi3z9\appDevDebugProjectContainer([
    'container.build_hash' => 'Pssi3z9',
    'container.build_id' => '657461e6',
    'container.build_time' => 1587567483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPssi3z9');
