<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerScxyyo5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerScxyyo5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerScxyyo5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerScxyyo5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerScxyyo5\appProdProjectContainer([
    'container.build_hash' => 'Scxyyo5',
    'container.build_id' => '820acedd',
    'container.build_time' => 1587560885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerScxyyo5');
