<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container08de4j9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container08de4j9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container08de4j9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container08de4j9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container08de4j9\appDevDebugProjectContainer([
    'container.build_hash' => '08de4j9',
    'container.build_id' => 'fd97a3e9',
    'container.build_time' => 1589327568,
], __DIR__.\DIRECTORY_SEPARATOR.'Container08de4j9');
