<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5wqj6zx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5wqj6zx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5wqj6zx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5wqj6zx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5wqj6zx\appDevDebugProjectContainer([
    'container.build_hash' => '5wqj6zx',
    'container.build_id' => '61d22a22',
    'container.build_time' => 1591820128,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5wqj6zx');
